import { describe, it, expect } from 'vitest';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { siteBasePath } from '../../tests/fixtures/session';

/**
 * Every scenario runs twice: once at the root, once under a base path.
 *
 * A site proxied under a subdirectory of a host whose root belongs to something
 * else (unipa at /annuaire behind WordPress) is the hardest shape we ship. A
 * URL the app builds without the prefix reaches that other thing rather than
 * the app, so those bugs appear there and nowhere else -- /web/entries
 * rendering "Aucune entrée" on a directory of 59 entries was invisible to this
 * suite until it ran against that shape.
 *
 * The arrangement: one pool of worker sites, lower half served at the root and
 * upper half under a prefix (scripts/e2e-workers.sh), with two playwright
 * projects -- chromium-root and chromium-base-path -- drawing from opposite
 * halves via `workerOffset`. So the same scenarios cover both shapes in one
 * run, rather than depending on which worker a scenario happened to land on.
 *
 * Three files have to agree, and each has broken independently:
 *   - scripts/e2e-workers.sh   writes BASE_PATH into .env.test.wN
 *   - siteBasePath()           reads those files, so navigation is prefixed
 *   - svelte.config.js         reads the file vite's --mode selects, so the
 *                              server is actually BUILT for that prefix
 *
 * A mismatch is silent in the worst way: the app serves one prefix while the
 * suite navigates to another, and every scenario fails with a 404 that reads as
 * a broken route rather than a misconfigured harness.
 *
 * Assumes the default E2E_WORKERS=8. The files are generated by
 * `scripts/e2e-workers.sh start`, so this is skipped when they are absent
 * rather than failing a unit run that never started the servers.
 */
const WORKERS = 8;
const ROOT_WORKERS = WORKERS / 2;
const all = Array.from({ length: WORKERS }, (_, i) => i);

const here = dirname(fileURLToPath(import.meta.url));
const envFile = (i: number) => resolve(here, '../..', `.env.test.w${i}`);

/**
 * The generated env files only exist while the worker servers are up --
 * `scripts/e2e-workers.sh start` writes them and `stop` removes them. Without
 * this guard the assertions below read every missing file as "served at the
 * root" and fail a plain `vitest run`, which is a lie about the configuration
 * rather than a finding about it.
 */
const workersRunning = all.every((i) => existsSync(envFile(i)));

describe.skipIf(!workersRunning)('worker site base paths', () => {
	it('serves the lower half at the root', () => {
		for (const i of all.slice(0, ROOT_WORKERS)) {
			expect(siteBasePath(i), `worker ${i} should be at the root`).toBe('');
		}
	});

	it('serves the upper half under a base path', () => {
		for (const i of all.slice(ROOT_WORKERS)) {
			expect(siteBasePath(i), `worker ${i} should carry the prefix`).toBe('/annuaire');
		}
	});

	it('covers both shapes, so neither can be dropped', () => {
		const shapes = new Set(all.map((i) => (siteBasePath(i) ? 'prefixed' : 'root')));
		expect(shapes).toEqual(new Set(['root', 'prefixed']));
	});
});
