FROM raviqqe/muffet:latest AS muffet

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=muffet /muffet /usr/local/bin/muffet
ENV LINKCHECK_ERROR_FILE=/tmp/linkcheck-errors.txt
COPY linkcheck.sh /usr/local/bin/linkcheck.sh
RUN chmod +x /usr/local/bin/linkcheck.sh
ENTRYPOINT ["/bin/sh", "/usr/local/bin/linkcheck.sh"]
