services:
  nodeserver_production:
    restart: always
    env_file:
      - .env
    build:
      context: .
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - "${NODE_PORT_EXTERNAL_PRODUCTION}:3000"
    environment:
      NODE_ENV: production
      ORIGIN: ${ORIGIN}