#!/usr/bin/env bash
#
# Regenerate a site's parent-menu file from the parent site's rendered home page.
#
# Run it by hand when the parent site's menu changes, then read the diff and
# commit it. Deliberately not automatic: the app would otherwise depend on
# WordPress being up and fast at render time, and an upstream menu change would
# reach production without anyone seeing it.
#
#     scripts/wp-menu-import.sh unipa
#
# The generated file lands in the skvar submodule, on whatever branch is checked
# out — skvar is one branch per site, so a menu committed on the wrong branch
# goes to the wrong site. The script prints the branch and refuses to overwrite
# a file belonging to a different parent site.
#
# Hand curation survives a re-run: hiding an item or renaming it is an edit to
# the generated file, and wp_menu_import.py merges those back in by href. See
# src/lib/wpMenuImport.test.ts, which pins that behaviour.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKVAR="$REPO_ROOT/src/routes/(skvar)"
OUT="$SKVAR/(var)/siteMenu.ts"
PY="$REPO_ROOT/scripts/wp_menu_import.py"

usage() {
	cat <<'EOF'
Usage: scripts/wp-menu-import.sh <context>

Contexts:
  unipa   dev.unipa.fr, app mounted at /annuaire

The context names the parent site and the base path, which must match the skvar
branch currently checked out and that site's BASE_PATH.
EOF
}

[ $# -eq 1 ] || { usage; exit 1; }

case "$1" in
	unipa)
		SITE_URL="https://dev.unipa.fr"
		BASE_PATH="/annuaire"
		SITE_NAME="UNIPA"
		SITE_LONG_NAME="Union Nationale des Infirmier·es en Pratique Avancée"
		LOGO="/wp-content/uploads/2025/06/unipa-logo-2025.png"
		LOGO_ALT="UNIPA — Union Nationale des Infirmier·es en Pratique Avancée"
		# The Skeleton theme matching this site, offered in the theme picker.
		# Written here so the app bar never has to name a tenant's theme.
		THEME="unipa"
		THEME_ICON="🩺"
		;;
	-h|--help) usage; exit 0 ;;
	*) echo "Unknown context: $1" >&2; usage; exit 1 ;;
esac

BRANCH="$(git -C "$SKVAR" branch --show-current)"
echo "Parent site : $SITE_URL"
echo "skvar branch: $BRANCH"

# The menu is written into whichever skvar branch is checked out. Writing unipa's
# menu onto another site's branch would put a foreign menu on that site, and the
# mistake is invisible until that site is built.
if [ -f "$OUT" ] && ! grep -q "$SITE_URL" "$OUT"; then
	echo >&2
	echo "Refusing to overwrite: $OUT exists and does not mention $SITE_URL." >&2
	echo "It probably belongs to another site. Check out that site's skvar branch" >&2
	echo "first (scripts/dev.sh $1 does this), or delete the file if it is stale." >&2
	exit 1
fi

# Re-apply existing curation. The previous tree is read back out of the module by
# stripping everything around the exported object, which is why the generated
# file keeps `items:` on its own line and is never hand-reformatted wholesale.
MERGE_ARGS=()
if [ -f "$OUT" ]; then
	if PRIOR="$(node -e '
		const fs = require("fs");
		const src = fs.readFileSync(process.argv[1], "utf8");
		const start = src.indexOf("export const siteMenu");
		const open = src.indexOf("{", start);
		const body = src.slice(open, src.lastIndexOf("};") + 1);
		// The module is generated, so its object literal is plain JSON apart
		// from the trailing semicolon; anything else means it was hand-edited
		// into a shape this cannot read, and the merge is skipped loudly.
		process.stdout.write(JSON.stringify(eval("(" + body + ")")));
	' "$OUT" 2>/dev/null)"; then
		MERGE_ARGS=(--merge-json "$PRIOR")
		echo "Merging curation from the existing file."
	else
		echo "WARNING: could not read the existing file; curation will be lost." >&2
		echo "         Review the diff carefully before committing." >&2
	fi
fi

echo "Fetching $SITE_URL ..."
HTML="$(curl -fsS --max-time 30 "$SITE_URL/")"

ITEMS="$(printf '%s' "$HTML" | python3 "$PY" \
	--site-url "$SITE_URL" --base-path "$BASE_PATH" "${MERGE_ARGS[@]}")"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
/**
 * The parent site's menu, as shown in this app's app bar and footer.
 *
 * GENERATED by scripts/wp-menu-import.sh from $SITE_URL — but edited by hand
 * afterwards, and those edits are kept: set \`hidden: true\` to drop an item and
 * its children, or change a \`label\` to rename one. A re-run merges both back in
 * by href, so curate here rather than keeping a second list somewhere else.
 *
 * Re-run when the parent site's menu changes, then read the diff.
 *
 * This file lives in the skvar submodule, which is one branch per site: nothing
 * here reaches any other site, and a site with no such file renders the shared
 * app bar and footer exactly as before.
 */

import type { SiteMenu } from '\$lib/interfaces/siteMenu.interface';

export const siteMenu: SiteMenu = {
	parentSite: {
		name: '$SITE_NAME',
		longName: '$SITE_LONG_NAME',
		url: '/',
		logo: '$LOGO',
		logoAlt: '$LOGO_ALT',
		theme: '$THEME',
		themeIcon: '$THEME_ICON'
	},
	items: $(printf '%s' "$ITEMS" | sed '1!s/^/\t/'),
	footer: {
		// The directory's own /sites page is not advertised on this site.
		showSites: false,
		// Contact is the parent site's — their address, not ours.
		contactHref: '/contact/',
		// Legal stays ours: this app is hosted by a different provider than the
		// parent site, so it owes its own mentions légales.
		legalHref: 'mentions-legales'
	}
};
EOF

echo
echo "Wrote $OUT"
echo "Review the diff, then commit inside the submodule:"
echo "    git -C 'src/routes/(skvar)' diff"
